### ISSUE TITLE
Overview of accepting businesses in a chosen area by map

### ISSUE THREAD

**Issue by RoAnBu** [ehrenamtskarte/ehrenamtskarte#10]
As an owner of a EAK, I want to get an overview of all accepting businesses in a chosen local area on a map, so that I know where I can benefit from discounts.

Acceptance criteria:

- [X] ~Local area could be chosen by PLZ~
- [x] Local area could be chosen by positioning function of the smartphone
- [x] Accepting businesses are point out by dots on the map

Technical tasks: #25, #26, #27

**Comment by elKei24** [comment]
Zip code search was migrated to #44.
