### ISSUE TITLE
Filter for accepting businesses

### ISSUE THREAD

**Issue by RoAnBu** [ehrenamtskarte/ehrenamtskarte#12]
As an owner of a EAK, I want to be able to search accepting businesses, so that I can find interesting locations more quickly.

Acceptance Criteria:
- [ ] I can filter by category of accepting business
- [ ] I can search using free text

**Comment by aiquita** [comment]
We should discuss whether the search result is shown as list or shown by pointing out the relevant locations on the map.

**Comment by RoAnBu** [comment]
Already done in #9.
