### ISSUE TITLE
App starts zoomed in even if no location available

### ISSUE THREAD

**Issue by Schedulaar** [ehrenamtskarte/ehrenamtskarte#123]
When starting the app without location services, the map is zoomed in too much.
Actually, if there is no location available, it should be zoomed out such that all of Bavaria is visible.

https://user-images.githubusercontent.com/7025199/103023838-fa0f3b80-454e-11eb-9bf7-20f163f0eab6.mov

**Comment by elKei24** [comment]
@Schedulaar is this still the case on your phone? At least on the emulator, I can not reproduce the bug.

**Comment by Schedulaar** [comment]
Hmm yeah, I think you need to allow location, but deactivate location services

**Comment by elKei24** [comment]
Seems like now more is broken than before 😢
