### ISSUE TITLE
Accepting businesses can have invalid categories

### ISSUE THREAD

**Issue by elKei24** [ehrenamtskarte/ehrenamtskarte#154]
**Describe the bug**
There is at least one accepting store (YOGA freiraum in Oberstimm near Ingolstadt) that has an invalid category index.

This causes the frontend to crash and the map to show a tiny, ugly app marker.

**Screenshots**
![Screenshot_2020-12-31-16-30-08-09_265fd09ea4905118dfcc6d305a1b3bc4](https://user-images.githubusercontent.com/13063245/103416183-d4ed7f00-4b85-11eb-8a69-f84a13995462.jpg)
![Screenshot_2020-12-31-16-29-59-67_265fd09ea4905118dfcc6d305a1b3bc4](https://user-images.githubusercontent.com/13063245/103416185-d9199c80-4b85-11eb-9020-3955c24eb982.jpg)

**Comment by RoAnBu** [comment]
Fixed now? @elKei24

**Comment by Schedulaar** [comment]
YOGA Freiraum has category 9 (sonstiges) now at least and there's no bug in the app anymore.
