### ISSUE TITLE
Provide way to recover digital EAK

### ISSUE THREAD

**Issue by PaulaWi** [ehrenamtskarte/ehrenamtskarte#18]
As an EAK owner I want to be able to add my EAK to the app again if I lost my phone or reinstalled the app.

Recovery option for #17 

Acceptance Criteria:

**Comment by RoAnBu** [comment]
I would close this for now because:
- The digital EAK can be added multiple times as long as you keep your qr code
- The EAK is personalized anyway
- If really necessary, the administration position can generate a new qr code
