### ISSUE TITLE
Initial setup of GraphQL

### ISSUE THREAD

**Issue by Schedulaar** [ehrenamtskarte/ehrenamtskarte#20]
GraphQL should be initially setup as an interface of the backend and frontend.
At the end of this task, there should be a working communication between backend and frontend via GraphQL.

**Comment by elKei24** [comment]
@Schedulaar done?

**Comment by Schedulaar** [comment]
Not sure, how well GraphQL is integrated in flutter... We could aim for a more type-safe interface, I think?
But we can also close the issue, as the inital setup does work.
