### ISSUE TITLE
Setup Flutter State Management

### ISSUE THREAD

**Issue by RoAnBu** [ehrenamtskarte/ehrenamtskarte#23]
Resources:
- https://github.com/brianegan/flutter_architecture_samples
- https://pub.dev/packages/provider
- https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple
- https://www.freecodecamp.org/news/how-to-handle-state-in-flutter-using-the-bloc-pattern-8ed2f1e49a13/

**Comment by RoAnBu** [comment]
Might not be necessary

**Comment by maxammann** [comment]
An example already is or was  in main.
Therefore this is already done.
