### ISSUE TITLE
Give Ausweisen Tab more structure

### ISSUE THREAD

**Issue by Schedulaar** [ehrenamtskarte/ehrenamtskarte#306]
As a user I don't want to be overwhelmed by all the options the Ausweisen tab provides for me.
As a EAK owner, I mostly only want to see my EAK and have the possibility to verify it (by viewing the QR code)
As a store owner, I mostly only want to have the possibility to verify others' EAK cards.

**Comment by RoAnBu** [comment]
@Schedulaar done?
