### ISSUE TITLE
"Auf Karte anzeigen" does not close an already opened details view

### ISSUE THREAD

**Issue by maxammann** [ehrenamtskarte/ehrenamtskarte#377]
**Describe the bug**

See below

**To Reproduce**
1. Go to Map view and open a detail view
2. Go to List view and open a detail view
3. Click on "Auf Karte anzeigen"
4. You see the previously opened detail view in step 1

**Expected behavior**

The detail view of step 1 should be closed.

**Comment by elKei24** [comment]
Duplicate of #173
