### ISSUE TITLE
About screen

### ISSUE THREAD

**Issue by elKei24** [ehrenamtskarte/ehrenamtskarte#57]
As the publisher of our app, I need to be sure that the user can easily find information about our app, at least including the used open source software and their licenses, in order to not getting sued. The About screen should be in german.

Acceptance Criteria:
- The About screen should show
  - [x] App Version
  - [x] Herausgeber
  - [x] Technische Umsetzung/Programmierung - https://github.com/ehrenamtskarte/ & "Wir"
  - [x] Server Betreiber - Wir bzw Digitalfabrik gGmbH
  - [x] Open Source Library licsenses:
      - Mapbox
      - Flutter
  - [x] License: MIT
  - [x] Haftung, Ausschluss und Disclaimer
  - [x] Datenschutzerklärung

Hint: We probably can achieve this very easily using Flutters [showAboutDialog](https://api.flutter.dev/flutter/material/showAboutDialog.html).

**Comment by maxammann** [comment]
![photo5411320663525928802](https://user-images.githubusercontent.com/905221/102978629-17b7b300-4505-11eb-94a9-a39bc2492ad8.jpg)
![photo5411320663525928803](https://user-images.githubusercontent.com/905221/102978634-18504980-4505-11eb-847a-f853db87c9ab.jpg)
![photo5411320663525928804](https://user-images.githubusercontent.com/905221/102978636-18504980-4505-11eb-9277-48cf48fcc34c.jpg)
![photo5411320663525928805](https://user-images.githubusercontent.com/905221/102978639-18e8e000-4505-11eb-9232-b5c8d2e3e50f.jpg)
![photo5411320663525928806](https://user-images.githubusercontent.com/905221/102978640-1a1a0d00-4505-11eb-8958-951a121aa88a.jpg)
