### ISSUE TITLE
Animate Navigation to Clicked Store On Map

### ISSUE THREAD

**Issue by Schedulaar** [ehrenamtskarte/ehrenamtskarte#97]
When the user clicks on a store on the map, the map currently jumps to the target.
Make it animated!

**Comment by elKei24** [comment]
Nice! I only had a first glance at it. So the previously broken behavior of animateCamera was caused by creating a new MapboxMap too often?

**Comment by Schedulaar** [comment]
Yeah, I noticed, that MapboxMap was created some time after the firing onClick... Not sure why, though...
